config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'pages#rests'
  get ':id' => 'pages#dishes', as: 'forest_show'
  get 'pages/adder', as: 'adder'
  get 'pages/deleter', as: 'deleter'
  get 'pages/alldeleter', as: 'alldeleter'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
	belongs_to :rest
	has_many :dishes
end

app/models/dish.rb
class Dish < ActiveRecord::Base
	belongs_to :rest
	belongs_to :category
end

app/models/rest.rb
class Rest < ActiveRecord::Base
	has_many :dishes
	has_many :categories

  has_attached_file :image,
                    styles: { medium: '300x300', thumb: '100x100'},
                    default_url: '/images/:style/missing.png'
  validates_attachment_content_type :image, 
                    content_type: ['image/jpeg', 'image/gif', 'image/png']
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def access_denied(exception)
    flash[:danger] = exception.message
    redirect_to root_url
  end

  before_action :configure_permited_parameters, if: :devise_controller?

  private

  def configure_permited_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone, :address])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @category = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to rests_path
    else
      render 'new'
    end
  end

  def destroy
    Category.destroy(params[:id])
    redirect_to rests_path
  end

  private

  def category_params
    category_params = params.require(:category).permit(:title, :rest_id)
  end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  def index
  	@dish = Dish.all
  end

  def new
  	@dish = Dish.new
  end

  def create
  	@dish = Dish.new(dish_params)

  	if @dish.save
  		redirect_to rests_path
  	else
  		render 'new'
  	end
  end

  def edit
    @dish = Dish.find(params[:id])
  end

  def update
    @dish = Dish.find(params[:id])

    if @dish.update(dish_params)
      redirect_to rests_path
    else
      render 'edit'
    end
  end

  def destroy
  	Dish.destroy(params[:id])
    redirect_to rests_path
  end

  private

  def dish_params
    dish_params = params.require(:dish).permit(:title, :price, :description, :counter, :category_id, :rest_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def rests
		@rests = Rest.all
	end

	def dishes
		@rest = Rest.find(params[:id])
		@categories = @rest.categories.to_a
	end

	def adder
		if Cart.last == nil
			@cart = Cart.create()
		end
  	@cart = Cart.last
		@dish = Dish.find(params[:format])
		if @dish.counter == nil
      @dish.counter = 0
    end
    if @dish.rest.id == @cart.cur_rest || @cart.cur_rest == nil
    	@cart.cur_rest = @dish.rest.id.to_i
    	@cart.save
    else
    	flash[:danger] = "You have added a dish from another restaurant. Your cart has been reset."
    	@cart.destroy
    	@cart = Cart.create
    	redirect_to alldeleter_path and return
    end
		@dish.counter += 1
		@dish.save
		redirect_to forest_show_path(@dish.rest.id) and return
	end

	def deleter
		@dish = Dish.find(params[:format])
		@dish.counter = 0
		@dish.save
		redirect_to forest_show_path(@dish.rest.id)
	end

	def alldeleter
		@dishes = Dish.all
		@dishes.each do |dish|
			dish.counter = 0
			dish.save
		end
		redirect_to forest_show_path(@dishes.first.rest.id)
	end
end

app/controllers/rests_controller.rb
class RestsController < ApplicationController
  def index
  	@rests = Rest.all
  end

  def new
  	@rest = Rest.new
  end

  def create
  	@rest = Rest.new(rest_params)

  	if @rest.save
  		redirect_to rests_path
  	else
  		render 'new'
  	end
  end

  def show
    @rest = Rest.find(params[:id])
    @dishes = @rest.dishes.to_a
  end

  def edit
    @rest = Rest.find(params[:id])
  end

  def update
    @rest = Rest.find(params[:id])

    if @rest.update(rest_params)
      redirect_to rests_path
    else
      render 'edit'
    end
  end

  def destroy
  	Rest.destroy(params[:id])
    redirect_to rests_path
  end

  private

  def rest_params
    rest_params = params.require(:rest).permit(:title, :description, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/new.html.erb
<h1>New category</h1>
<% if @category.errors.any? %>
	<div class="errors">
		Total number of errors: <%= @category.errors.count %>
	</div>
<% end %>

<%= form_for @category do |f| %>
	<div>
		<%= f.label :rest_id %>
		<%if @category.errors[:rest_id].any? %>
			<div class="errors">
			<ul>
				<% @category.errors[:rest_id].each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		<% end %>
		<br>
		<%= f.collection_select :rest_id, Rest.all, :id, :title, :include_blank => true %><br>
	</div>

	<div>
		<%= f.label :title %>
		<%if @category.errors[:title].any? %>
			<div class="errors">
			<ul>
				<% @category.errors[:title].each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		<% end %>
		<br>
		<%= f.text_field :title %><br>
	</div>

	<div>
		<%= f.submit %>
	</div>
<% end %>

app/views/dishes/_form.html.erb
<% if @dish.errors.any? %>
	<div class="errors">
		Total number of errors: <%= @dish.errors.count %>
	</div>
<% end %>

<%= form_for @dish do |f| %>
	<div>
		<%= f.label :rest_id %>
		<%if @dish.errors[:rest_id].any? %>
			<div class="errors">
			<ul>
				<% @dish.errors[:rest_id].each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		<% end %>
		<br>
		<%= f.collection_select :rest_id, Rest.all, :id, :title, :include_blank => true %><br>
	</div>

	<div>
		<%= f.label :category_id %>
		<%if @dish.errors[:category_id].any? %>
			<div class="errors">
			<ul>
				<% @dish.errors[:category_id].each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		<% end %>
		<br>
		<%= f.collection_select :category_id, Category.all, :id, :title, :include_blank => true %><br>
	</div>

	<div>
		<%= f.label :title %>
		<%if @dish.errors[:title].any? %>
			<div class="errors">
			<ul>
				<% @dish.errors[:title].each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		<% end %>
		<br>
		<%= f.text_field :title %><br>
	</div>

	<div>
		<%= f.label :price %>
		<%if @dish.errors[:price].any? %>
			<div class="errors">
			<ul>
				<% @dish.errors[:price].each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		<% end %>
		<br>
		<%= f.text_field :price %><br>
	</div>

	<div>
		<%= f.label :description %>
		<%if @dish.errors[:description].any? %>
			<div class="errors">
			<ul>
				<% @dish.errors[:description].each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		<% end %>
		<br>
		<%= f.text_area :description %><br>
	</div>

	<%= f.hidden_field :counter, value: 0 %>

	<div>
		<%= f.submit %>
	</div>
<% end %>

app/views/dishes/edit.html.erb
<h1>Edit dish</h1>
<%= render 'form' %>

app/views/dishes/new.html.erb
<h1>New dish</h1>
<%= render 'form' %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Food</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Food</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'FetchFood', root_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="#">About</a></li>
        <li><a href="#">Contacts</a></li>
      </ul>
      <ul class="navbar-nav navbar-right">
        <% if user_signed_in? %>
          <p class="navbar-text">
            Hello, <%= link_to current_user.name, edit_user_registration_path(current_user), class: 'navbar-link' %>
          </p>
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Edit profile', edit_user_registration_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          </ul>
        <% else %>
          <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-default navbar-btn' %>
          <%= link_to 'Log in', new_user_session_path, class: 'btn btn-default navbar-btn' %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<br>
<br>
<br>
<br>
<br>
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<br>
<style type="text/css">
  #main-content{
    width: 70%;
    float: left;
  }
  #side-content{
    width: 30%;
    float: right;
  }
</style>
<div class="wrapper">
  <div id="main-content">
      <%= yield %>
  </div>
  <div id="side-content">
      <%= yield(:side_bar) %>
  </div>
</div>

</body>
</html>

app/views/pages/_cart.html.erb
<% if current_user == nil %>
  You should be logged in to use the cart.
<% else %>
  <h2>Cart:</h2>
  <% @dishes = Dish.all %>
  <ul>
    <% sum = 0 %>
    <% @dishes.each do |dish| %>
      <% if dish.counter == nil
        dish.counter = 0
        end %>
      <% if dish.counter > 0 %>
        <% add = dish.counter.to_i * dish.price.to_f %><%  sum = sum + add.to_f %>
        <li name=<%= "#{dish.title}" %>  price=<%= "#{dish.price}" %> counter=<%= "#{dish.counter}" %>><%= dish.title + " " + dish.counter.to_s + " x " + dish.price.to_s + " сом  " %><br><%= link_to 'Delete', deleter_path(dish), class: 'btn btn-danger' %></li>
      <% end %>
    <% end %>
  </ul>
  <h3 id="alldeleter">Total: <%= sum %> сом</h3>
  <%= link_to 'Empty cart', alldeleter_path, class: 'btn btn-danger' %>
<% end %>

app/views/pages/dishes.html.erb
<h1><%= @rest.title %></h1>
<h4><%= @rest.description %></h4>
<br>
<br>
<% @categories.each do |category| %>
	<h3><%= category.title %></h3>
	<% @dishes = category.dishes.to_a %>
	<% @dishes.each do |dish| %>
		<tr>
			<td><div class="col-md-2"><%= dish.title %></div></td>
			<td><div class="col-md-2"><%= dish.price %> сом</div></td>
			<td><div class="col-md-3"><%= dish.description %></div></td>
			<% unless current_user == nil %>
				<td><div class="col-md-2"><%= link_to 'Add to cart', adder_path(dish), class: 'btn btn-success' %></div></td>
			<% end %>
			<br>
			<br>
			<br>
		</tr>
	<% end %>
<% end %>

<% content_for(:side_bar) do %>
	<% render 'cart' %>
<% end %>

app/views/pages/rests.html.erb
<h1>Restaurants list</h1>
<br>
<br>
<table class="container">
	<tr class="row">
		<th><div class="col-md-2">Title</div></th>
		<th><div class="col-md-2">Description</div></th>
		<th><div class="col-md-2">Image</div></th>
	</tr>
	
	<% @rests.each do |rest| %>

	<tr class="row">
		<td><div class="col-md-3"><%= link_to rest.title, forest_show_path(rest), class: 'btn btn-primary' %></div></td>
		<td><div class="col-md-10"><%= rest.description %></div></td>
		<td class="col-md-6"><%= image_tag rest.image.url(:medium) %></td>
	</tr>

	<% end %>
</table>

<% content_for(:side_bar) do %>
	<% render 'cart' %>
<% end %>

app/views/rests/_form.html.erb
<% if @rest.errors.any? %>
	<div class="errors">
		Total number of errors: <%= @rest.errors.count %>
	</div>
<% end %>

<%= form_for @rest do |f| %>
	<div>
		<%= f.label :title %>
		<%if @rest.errors[:title].any? %>
			<div class="errors">
			<ul>
				<% @rest.errors[:title].each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		<% end %>
		<br>
		<%= f.text_field :title %><br>
	</div>

	<div>
		<%= f.label :description %>
		<%if @rest.errors[:description].any? %>
			<div class="errors">
			<ul>
				<% @rest.errors[:description].each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		<% end %>
		<br>
		<%= f.text_area :description %><br>
	</div>

	<div>
		<%= f.label :image %><br>
		<%= f.file_field :image %><br>
	</div>

	<div>
		<%= f.submit %>
	</div>
<% end %>

app/views/rests/edit.html.erb
<h1>Edit cafe</h1>
<%= render 'form' %>

app/views/rests/index.html.erb
<h1>Restaurants list</h1>

<div class="row">
	<div class="col-md-1">
		<%= link_to 'Create rest', new_rest_path, class: 'btn btn-primary' %>
	</div>
</div>
<br>
<br>
<br>
<table>
	<tr>
		<th><div class="col-md-1">Title</div></th>
		<th><div class="col-md-1">Description</div></th>
		<th><div class="col-md-1">Image</div></th>
		<th>Actions</th>
	</tr>
	
	<% @rests.each do |rest| %>

	<tr>
		<td><div class="col-md-1"><%= link_to rest.title, rest_show_path(rest), class: 'btn btn-primary' %></div></td>
		<td><div class="col-md-1"><%= rest.description %></div></td>
		<td><div class="col-md-1"><%= image_tag "/upl/rests/#{rest.image}", size: '100' %></div></td>
		<td>
			<%= link_to 'Edit', rest_edit_path(rest), class: 'btn btn-warning' %>
			<%= link_to 'Delete', rest_path(rest), class: 'btn btn-danger',
									method: :delete,
									data: {confirm: 'Realy?'}
			 %>
		</td>
	</tr>

	<% end %>
</table>

app/views/rests/new.html.erb
<h1>New cafe</h1>
<%= render 'form' %>

app/views/rests/show.html.erb
<h1><%= @rest.title %></h1>
<br>
<%= link_to 'New Dish', new_dish_path, class: 'btn btn-primary' %>
<%= link_to 'New Category', new_category_path, class: 'btn btn-primary' %>
<br>
<br>
<br>
<table>
	<tr>
		<th>Title</th>
		<th>Price</th>
		<th>Description</th>
		<th>Actions</th>
	</tr>

	<% @dishes.each do |dish| %>

	<tr>
		<td><%= dish.title %></td>
		<td><%= dish.price %></td>
		<td><%= dish.description %></td>
		<td>
			<%= link_to 'Edit', dish_edit_path(dish), class: 'btn btn-warning' %>
			<%= link_to 'Delete', dish_path(dish), class: 'btn btn-danger',
									method: :delete,
									data: {confirm: 'Realy?'}
			 %>
		</td>
	</tr>

	<% end %>
</table>

app/views/shared/_field_errors.html.erb
<% if object.errors[field_name].any? %>
    <ul class="error-messages">
      <% object.errors.full_messages_for(field_name).each do |error| %>
          <li><%= error %></li>
      <% end %>
    </ul>
<% end %>